import Head from "next/head";
import styles from "@src/styles/home/home.module.scss";
import { HomeSection } from "@src/containers/Home";
import { AboutSection } from "@src/containers/About";
import { Services } from "@src/containers/Services";
import { Portfolio } from "@src/containers/Portfolio";
import { Blogs } from "@src/containers/Blogs";
import { Contacts } from "@src/containers/Contacts";

export default function Home() {
  return (
    <>
      <Head>
        <title>Dung Bui Tien - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <HomeSection />
        <AboutSection />
        <Services />
        <Portfolio />
        <Blogs />
        <Contacts />
      </div>
    </>
  );
}
